A small benchmark and dockerfile
clecat/ocaml-matrix pull request #12
Opened 2022-01-04 18:01 UTC by TheLortex

## Added a Dockerfile

This dockerfile will be useful when deploying the server

## Benchmarking

The benchmark is simple for now:
- it starts the server in a fresh context
- then send 128 messages with two parameters: the number of rooms and the maximum number of connections

On my laptop it takes from 1 to 3 seconds.

2022-01-05 00:51 UTC, zapashcanon commented on Makefile
> +	@dune exec -- ./bench/bench.exe --json --minimal --nb-exec 3
`bench/bench.exe` ? the `./` is not required

2022-01-05 09:14 UTC, TheLortex commented on Makefile
> +	@dune exec -- ./bench/bench.exe --json --minimal --nb-exec 3
Oops that's wrong indeed. It's just `dune build @bench` for now.

2022-01-05 15:45 UTC, clecat commented
Thank you a lot for this benchmark

2022-01-05 15:52 UTC, clecat requested changes

2022-01-05 15:52 UTC, clecat commented on ci-server/client_routes.ml
> +            Dream.json ~status:`Unauthorized {|{"errcode": "M_FORBIDDEN", "error": "Wrong password"}|}
Should we really give out that information ?
At least we should reply with a "Wrong usename or password"

2022-01-05 15:52 UTC, clecat commented on ci-server/client_routes.ml
> +          Dream.json ~status:`Unauthorized {|{"errcode": "M_FORBIDDEN", "error": "Missing password in store"}|}
This error case means that the user does not exist, as a password will always be here if a user is here.
Therefore we do not want to send back this message, but more something like "Wrong username or password"

2022-01-06 13:35 UTC, clecat commented
Thank you

2022-01-06 13:35 UTC, merged